- lib/dry/system/container.rb
- spec/unit/container_spec.rb
Hi ! 
Here's a small change discussed in #35 
Closes #35 
Closes #34
> Perform registration even though component already required

- dry-system.gemspec
- lib/dry/system/container.rb
- spec/integration/boot_spec.rb
- spec/unit/container_spec.rb
> Deprecate `#boot` and `#boot!` methods

- lib/dry/system/auto_registrar.rb
- lib/dry/system/booter.rb
- lib/dry/system/component.rb
- lib/dry/system/components/bootable.rb
- lib/dry/system/container.rb
- lib/dry/system/provider.rb
Solves #54 
Also, I clean some files that were no using the already defined constants we have `RB_EXT` and `RB_GLOB`.
> Move boot related method from component

- lib/dry/system/auto_registrar/configuration.rb
- lib/dry/system/container.rb
This fixes some typos in docs.
> Typo fixes in comments

- lib/dry/system/constants.rb
- lib/dry/system/settings.rb
- spec/integration/settings_component_spec.rb
Fix #85 
@solnic @andrewcroome raise a better error if the setting value is incorrect.
> raises a meaningful error if the value for a setting is incorrect

- Gemfile
- lib/dry/system/container.rb
As far as I can see, we need to remove one line. See details in https://github.com/dry-rb/dry-configurable/pull/59 and https://github.com/dry-rb/dry-container/pull/52
> dry-configurable & dry-container compatibility changes

- .travis.yml
All specs passed. For now, I would allow to fail to run them in TruffleRuby
> Run specs in TruffleRuby on Travis CI

- examples/standalone/system/container.rb
- lib/dry/system/plugins/dependency_graph.rb
- spec/integration/container/plugins/dependency_graph_spec.rb
> Send register class name to instrumentation register event in DG plugin

- lib/dry/system/plugins/dependency_graph.rb
- spec/integration/container/plugins/dependency_graph_spec.rb
Reference to https://github.com/dry-rb/dry-system/pull/115#discussion_r290640614
> Fix incorrect name for DG plugin payload

- lib/dry/system/constants.rb
- lib/dry/system/plugins.rb
- lib/dry/system/plugins/bootsnap.rb
- lib/dry/system/plugins/dependency_graph.rb
- lib/dry/system/plugins/monitoring.rb
- lib/dry/system/plugins/notifications.rb
- spec/integration/container/plugins_spec.rb
> Clear exception message when an external dep is missing

- dry-system.gemspec
- lib/dry/system/container.rb
- spec/integration/container/plugins_spec.rb
* override `setting` so that it works with customized plugin settings
* bump dep on dry-configurable to ~> 0.11
> Make it possible for plugins to add their own settings

- dry-system.gemspec
- lib/dry/system/container.rb
- project.yml
> Fix compatibility with dry-configurable

- lib/dry/system/identifier.rb
- spec/unit/identifier_spec.rb
> Fix behavior of Dry::System::Identifier#start_with?. 

- project.yml
This dry-container release also includes adjustments for the dry-configurable 0.13.0 API
> Depend on dry-container 0.9.0

- examples/custom_configuration_auto_register/lib/entities/user.rb
- examples/custom_configuration_auto_register/lib/user_repo.rb
- examples/custom_configuration_auto_register/run.rb
- examples/custom_configuration_auto_register/system/container.rb
- examples/standalone/lib/empty_service.rb
- examples/standalone/lib/not_registered.rb
- examples/standalone/lib/service_with_dependency.rb
- examples/standalone/lib/user_repo.rb
- examples/standalone/run.rb
- examples/standalone/system/container.rb
This PR fixes the examples.
Best regards!
> Fix dry system examples

- lib/dry/system/provider.rb
- spec/integration/container/providers/resolving_root_key_spec.rb
> Ensure a provider cannot implicitly re-run itself while in the process of running

- lib/dry/system/errors.rb
- lib/dry/system/loader.rb
- spec/fixtures/components/test/bar/abc.rb
- spec/unit/auto_registrar_spec.rb
- spec/unit/errors_spec.rb
- spec/unit/loader_spec.rb
Addresses #147, with "Did you mean?" support
> Raise ComponentNotLoadableError with helpful dry-system messages

- lib/dry/system/plugins/zeitwerk.rb
Make it work better with users or third party systems (like Hanami) wanting to push their own dirs into the loader by setting the loader as early as possible. This allows the dirs to be pushed before the `loader.setup` that is run in the plugin's after-`configure` block.
> Improve Zeitwerk plugin flexibility

- lib/dry/system/identifier.rb
- spec/unit/identifier_spec.rb
This expands upon our range of helpful `Identifier` predicates and resolves #171.
> Add Identifier#end_with? and #include?

- Gemfile
- dry-system.gemspec
- lib/dry/system/container.rb
- lib/dry/system/stubs.rb
- spec/integration/container/lazy_loading/auto_registration_disabled_spec.rb
- spec/integration/container/providers/conditional_providers_spec.rb
Follow-up after dry-rb/dry-core#77
> Switch to Dry::Core::Container

- docsite/source/settings.html.md
> Fix a code example in settings

- docsite/source/settings.html.md
The documentation missed this requirement. I found it here https://github.com/dry-rb/dry-rails/issues/55#issuecomment-1285873454
> Fix the settings example code
