dry-rb/dry-system

lib/dry/component/config.rb, spec/fixtures/test/config/subapp.yml, spec/unit/config_spec.rb
There's currently an error where you can't have multiple `yml` config files for different components.
Because `Dry::Component::Config` would get "locked" with the first loaded file's keys.
=> Multiple config files

README.md
After working with the code I found that I needed to pass a Pathname _and_ make it relative to the working directory with `./`. It's a minor thing but hopefully it'll help newcomers experimenting with this.
This is related to #7
=> Fixes missing readme info about the path

.travis.yml, Gemfile, lib/dry/component/container.rb, lib/dry/component/injector.rb, spec/spec_helper.rb, spec/unit/container/import_spec.rb, spec/unit/container_spec.rb, spec/unit/injector_spec.rb
Support all injector types offered by dry-auto_inject (args, hash, kwargs) while still auto-loading component files as required.
This changes `Container.import_module` to `Container.Inject`, which now returns an `Injector` object that offers API to inject with each of the strategies, e.g.
```ruby
class MyContainer < Dry::Component::Container
end
class MyClass
include MyContainer.Inject["foo.bar"]
include MyContainer.Inject.hash["foo.bar"]
include MyContainer.Inject.kwargs["foo.bar"]
end
```
The `Injector` also supports the new dry-auto_inject dependency aliasing API (e.g. `Inect[local_name: "container.name"]`).
This is a work in progress. I'm putting this PR up now for your feedback!
One change I would like to make is to be able to access the Injector via `::` syntax, e.g. `include …
=> Support all dry-auto_inject injector types

lib/dry/component/injector.rb, spec/unit/injector_spec.rb
Before, you could only declare an injector strategy once, e.g.
```ruby
MyContainer::Inject.kwargs["foo.bar"]
```
This would be fine if we accept that the standard "args" injector was the one everyone uses by default, e.g.
```ruby
MyApp::Import = MyContainer::Inject
class MyClass
include MyApp::Import["foo.bar"]
end
```
However, this strategy swapping limitation would be a problem if you wanted to use an alternative default strategy. While this would work fine:
```ruby
MyApp::Import = MyContainer::Inject.kwargs
class MyClass
include MyApp::Import["foo.bar"]
end
```
It would mean that you could then no longer swap strategies on a case by case basis:
```ruby
MyApp::Import = MyContainer::Inject.kwargs
class MyClass
include MyApp::Import.hash["foo.bar"]
end
```
This change will allow this to …
=> Cache injector strategies properly and allow arbitrary strategy swapping

lib/dry/component/container.rb, lib/dry/component/injector.rb, spec/unit/container/import_spec.rb, spec/unit/container/injector_spec.rb, spec/unit/container_spec.rb, spec/unit/injector_spec.rb
Allow `Dry::AutoInject` options to be passed to `Dry::Component::Container#injector`. This allows the underlying auto_inject object to be configured as the user requires, while still retaining dry-component's desired behaviour of lazily loading dependencies.
The immediate benefit of this is that a user can now set up an injector with their own custom strategies container. However, it does mean that any options added to dry-auto_inject in the future will automatically be available for dry-component's injector as well.
This requires a breaking behavioural change, though. The `Inject` constant that we were setting up automatically on `Dry::Component::Container` subclasses can't be set up in the same way anymore, since there's no way we can infer by that time if the user wants any particular …
=> Support all auto inject strategies

lib/dry/component/container.rb, lib/dry/component/loader.rb, spec/fixtures/components/namespaced/bar.rb, spec/fixtures/components/namespaced/foo.rb, spec/unit/container/auto_register_spec.rb, spec/unit/loader_spec.rb
When a user sets a default namespace on a container, that namespace will not be used in any container registrations for components from within that namespace. This makes it easier to reference them later.
For example, in a container with a namespace of “foo.bar”, a component at “foo/bar/baz.rb” will be accessible on the identifier “baz” only (with the default namespace removed for convenience).
There are a few design adjustments to make this possible:
- The container's configured `loader` is instantiated with the container object being passed to it. This allows the loader to inspect the container for config and various other settings.
- The `loader` object no longer represents a single loaded component file, but instead should offer `#load(file)`, which _then_ returns an object to …
=> Add configurable default namespace to containers

lib/dry/component/container.rb, spec/unit/container_spec.rb
We ran into an issue with lazy loading when unit testing one of our in-development dry-web apps.
Here's the scenario. In a "main" sub-app (whose container imports our app's main umbrella container into the "core" namespace), we had an operation depend on one of the bootable dependencies from the umbrella container:
`apps/main/lib/main.subscribe_to_newsletter.rb`:
```ruby
require "main/import"
MyApp::Container.boot! :mailchimp
module Main
class SubscribeToNewsletter
include Main::Import["core.mailchimp"]
def call(input)
end
end
end
```
The mailchimp dependency boot file looked like this:
`umbrella/boot/mailchimp.rb`:
```ruby
require "mailchimp"
MyApp::Container.register "mailchimp", Mailchimp::API.new(api_key_goes_here)
```
When unit testing `SubscribeToNewsletter` (i.e. when none of the …
=> Return immediately from load_component if the key already exists

dry-system.gemspec, lib/dry/system/component.rb, lib/dry/system/container.rb, lib/dry/system/errors.rb, lib/dry/system/loader.rb, spec/fixtures/umbrella/component/boot/db.rb, spec/integration/import_spec.rb, spec/unit/component_spec.rb, spec/unit/container/auto_register_spec.rb, spec/unit/container_spec.rb, spec/unit/loader_spec.rb
This improves separation of concerns and allows lazy-loading bootable deps.
=> Refactor Container/Component/Loader

examples/standalone/run.rb
Running the standalone example results in an error:
`cannot load such file -- dry/system/container (LoadError)`
This PR adds the necessary require statement to get the bundler environment up and running.
=> Standalone example needs 'bundler/setup' to run

lib/dry/system/lifecycle.rb, spec/unit/container/finalize_spec.rb
@solnic I couldn't improve/simplify the spec examples you [suggested](https://github.com/dry-rb/dry-system/issues/29#issuecomment-241490760). More specifically, I intended to extract the finalization and boot code and DRY things up a bit. However, this would require additional helper method(s) and that seemed like an overkill to me.
Also, I hope the example description is good.
BTW, I believe`spec/fixtures/test/log/test.log` should be ignored, right?
=> Fix silent failures on undefined methods or variables (#29)

lib/dry/system/container.rb
In line 69 `system_dir` has `system` value.
=> Fix system_dir value in comments

lib/dry/system/auto_registrar.rb, lib/dry/system/component.rb, lib/dry/system/container.rb, lib/dry/system/magic_comments_parser.rb, spec/fixtures/components/no_register.rb, spec/fixtures/magic_comments/comments.rb, spec/unit/container/auto_register_spec.rb, spec/unit/magic_comments_parser_spec.rb
Auto-registration is one of my favourite dry-system features, and our usual practice has been to point it at our entire `lib/` folders and have it auto-register everything.
The problem is, there's a lot of files in there (e.g. entity or value classes) that don't need to be available in the container - those files we `require` directly and then instantiate their classes directly.
Now, it's mostly harmless for dry-system to register these, but it'd be nice if it didn't. We only want useful registrations in our containers.
One option would be to move these files into a totally separate directly structure, one which the auto-registrar doesn't look at, but that's a big disturbance to our file structure due to some implementation detail of dry-system. We don't want the tail to wag the dog. …
=> Control auto-registration via magic comments

examples/custom_configuration_auto_register/Gemfile, examples/custom_configuration_auto_register/lib/entities/user.rb, examples/custom_configuration_auto_register/lib/user_repo.rb, examples/custom_configuration_auto_register/run.rb, examples/custom_configuration_auto_register/system/boot/persistence.rb, examples/custom_configuration_auto_register/system/container.rb, examples/custom_configuration_auto_register/system/import.rb, lib/dry/system/auto_registrar.rb, lib/dry/system/auto_registrar/configuration.rb, lib/dry/system/container.rb, spec/unit/auto_registrar/configuration_spec.rb, spec/unit/container/auto_register_spec.rb
This implements https://github.com/dry-rb/dry-system/issues/46
@timriley is we mention this add the ability to skip `auto_registration` via configuration.
=> Skip auto registration via config

lib/dry/system/constants.rb, lib/dry/system/container.rb, lib/dry/system/manual_registrar.rb, spec/fixtures/manual_registration/container/foo.rb, spec/fixtures/manual_registration/lib/test/foo.rb, spec/integration/container/lazy_loading/manual_registration_spec.rb
This PR makes manual registration files a proper, configurable part of the container setup.
One benefit of this is that we can now attempt to load a matching manual registration file during lazy loading, which, alongside the lazy loading of bootable deps, means there should be no gaps in what kind of things can be lazily loaded during development.
Resolves #33.
@solnic @AMHOL – what do you think? If you're happy with this direction I'll add more tests to ensure everything's covered.
In working through this, I noticed a few structural things I'd like to improve later. I'm not sure if e.g. `Component#bootable?` and `#boot_file?` should exist - it feels like that's the component knowing too much about other parts of the system. Would it be cleaner for this to be provided by something like …
=> Establish concept of manual registrations in Container (and support lazy loading)

lib/dry/system/booter.rb, lib/dry/system/errors.rb, spec/fixtures/other/config/boot/hell.rb, spec/fixtures/test/system/boot/hell.rb, spec/unit/container_spec.rb
This solve #38 
@timriley, @solnic  I don't know if you have it in the roadmap or we do not want to raise such error. But I thought to give it a try since it looks quite simple to implement.
=> Raise error when missmatch between boot filename and registered component

lib/dry/system/container.rb, spec/integration/import_spec.rb, spec/unit/container/import_spec.rb
This PR makes it so that `Dry::System::Container.import` requires you to pass a hash of names and containers, instead of supporting containers on their own and using their configured names implicitly.
The rationale for this is that when you're importing one container into another, you should be making a clear decision about the local name to use for that imported container. This isn't much extra work at all, but makes for a lot of extra clarity around the behavior of the imported containers.
=> Require explicitly given names for imported containers

lib/dry/system/component.rb, lib/dry/system/errors.rb, spec/fixtures/multiple_namespaced_components/multiple/level/baz.rb, spec/fixtures/multiple_namespaced_components/multiple/level/foz.rb, spec/unit/component_spec.rb, spec/unit/container/auto_register_spec.rb
Solves #40 
Remove unused Error class and tweak `ensure_valid_identifier ` to allow multilevel directories
=> Allow default_namespace to declare multilevel directories

dry-system.gemspec, lib/dry/system/container.rb, lib/dry/system/manual_registrar.rb, spec/unit/container/config_spec.rb
This is helpful because new users may reasonably provide a string value for this config and we shouldn't give them an error in return for this.
=> Accept plain string paths for container’s config.root

lib/dry/system/component.rb, spec/unit/component_spec.rb
Solves #50 
Apart from allowing the same in the path, this change raises and exception if the namespace set up for the component is not found in the path
=> Allow same key two occur multiple times in path

lib/dry/system/container.rb, lib/dry/system/stub.rb, lib/dry/system/stubs.rb, spec/fixtures/stubbing/lib/stubbing/car.rb, spec/fixtures/stubbing/system/boot/mock.rb, spec/spec_helper.rb, spec/unit/container_spec.rb
Solves #49 
After giving some thoughts and looking at how we implement stubbing in `dry-container` I came up with this solution.
There a few things I do not like is that the `finalize!` method in the `Stub` module is practically the same except for the `freeze` part.
I had other implementation where we pass an argument to `finalize!` method making `freeze` control by this arguments.
```ruby
def finalize!(testing: false, &block)
return self if frozen?
yield(self) if block
importer.finalize!
booter.finalize!
manual_registrar.finalize!
auto_registrar.finalize!
freeze unless testing
end
```
And inside the `Stub` module we can simply.
```ruby
def finalize!(&block)
super(testing: true, &block)
end
```
Or even in test the user can say `finalize(testing: true)` without the need of the `Stub` …
=> Added enabled_stubs! for testing finalize! containers

lib/dry/system.rb, lib/dry/system/booter.rb, lib/dry/system/booter/component_registry.rb, lib/dry/system/components/bootable.rb, lib/dry/system/components/external.rb, lib/dry/system/container.rb, lib/dry/system/errors.rb, lib/dry/system/lifecycle.rb, lib/dry/system/provider.rb, lib/dry/system/provider_registry.rb, spec/fixtures/external_components/alt-components/logger.rb, spec/fixtures/external_components/components/logger.rb, spec/fixtures/external_components/lib/external_components.rb, spec/integration/external_components_spec.rb, spec/spec_helper.rb, spec/unit/container/finalize_spec.rb, spec/unit/container_spec.rb
This adds support for external components. To enable this we need to add a couple of new concepts, like a component provider and external component. This is still a WIP, but I got things figured out, so I'll clean this up and should be ready to go.
``` ruby
require "dry/system"
Dry::System.register_provider(
:external_components,
boot_path: Pathname(__dir__).join('../components').realpath
)
require "dry/system"
Dry::System.register_component(:logger, provider: :external_components) do
init do
module ExternalComponents
class Logger
end
end
end
start do
register(:logger, ExternalComponents::Logger.new)
end
end
require "external_components"
class MyContainer < Dry::System::Container
register_external(:logger, provider: :external_components)
end
class MyContainer < Dry::System::Container …
```
=> 3rd party bootable components

lib/dry/system/component.rb, spec/unit/component_spec.rb, spec/unit/container/auto_register_spec.rb
@solnic as we talk about. This allows booting the component without namespace in its identifier
=> Allow instantiate component without namespace in its identifier

dry-system.gemspec, lib/dry/system/components.rb, lib/dry/system/components/bootable.rb, lib/dry/system/components/config.rb, lib/dry/system/lifecycle.rb, lib/dry/system/provider_registry.rb, lib/dry/system/settings.rb, lib/dry/system/settings/file_loader.rb, lib/dry/system/settings/file_parser.rb, lib/dry/system/system_components/settings.rb, spec/fixtures/external_components/components/logger.rb, spec/fixtures/settings_test/.env, spec/integration/boot_spec.rb, spec/integration/external_components_spec.rb, spec/integration/settings_component_spec.rb, spec/spec_helper.rb
This introduces built-in `:system_components` with the very first one called `:settings`. It also adds `settings` DSL for bootable components where you can define structure of your settings with setting keys and their types (and it enforces strict types).
Example usage:
``` ruby
class MyApp < Dry::System::Container
boot :settings, from: :system_components do
settings do
key :database_url, type(String).constrained(filled: true)
end
end
end
MyApp[:settings].database_url
```
Bootable components can ship with their settings predefined too:
``` ruby
Dry::System.register_component(:logger, provider: :some_provider) do
setttings do
key :output, type('Any').default($stdout)
key :level, type(Symbol).default(:debug)
end
start do
require 'some_provider/logger'
register(:logger, …
```
=> Add built-in :system_components with :settings component

lib/dry/system/container.rb, spec/integration/settings_component_spec.rb, spec/unit/container_spec.rb
Fixes #64 
@solnic @timriley I rename `Container.require` to `Container.require_from_root`. Along the way, I updated some documentation and replace some `Kernel.require` for plain `require`
=> Rename Container.require to Container.require_from_root

Gemfile, lib/dry/system/plugins.rb, lib/dry/system/plugins/decorate.rb, lib/dry/system/plugins/monitoring.rb, lib/dry/system/plugins/notifications.rb, spec/unit/container/decorate_spec.rb, spec/unit/container/monitor_spec.rb, spec/unit/container/notifications_spec.rb
This adds 3 plugins:
- `:decorate` a trivial plugin that allows re-registering an object by wrapping it with provided decorator
- `:notifications` copy/paste from dry-web
- `:monitoring` adds `monitor` method which enables object monitoring on top of notification system
=> Add notifications + monitoring plugins

lib/dry/system/plugins/monitoring/proxy.rb
@solnic I was reading the code and notice that we could use the already defined variable in `proxy.rb`
If you prefer to use the inline style, let me know and I will remove the upper variable assigment
=> Use variable already allocated for monitored_methods

lib/dry/system/component.rb, spec/unit/component_spec.rb
Solves #75 
At component initialization, we extract the namespace option from the identifier, the regex we use need a little improvement.
```ruby
component = Dry::System::Component.new(:mailer, namespace: "mail", separator: ".")
componet.identifier # => mailer
```
=> Fix Component . Extracting namespace from identifier 

lib/dry/system/container.rb, lib/dry/system/loader.rb
Yard does not require (and reports as invalid) ```*``` in arguments. This PR fixes that.
https://app.coditsu.io/dry-rb/builds/validations/056fe6ff-7d94-4634-ad73-805e42be0c1e/offenses?q[offense_name_cont]=UnknownParameterName
=> yard proper parameter names

lib/dry/system/settings.rb, spec/integration/settings_component_spec.rb
Fixes #84 
@solnic @andrewcroome I was able to track the issue down. Basically, we where explicitly passing the value as `nil` if the value wasn't found in `ENV` or in any of the `.env` files. To solve we just need not pass the key to the `Dry::Struct` `new` method.
So with this change instead of passing `{an_int: nil}` we pass `{}` and it will use the default value. Also this change in `Dry::Struct` helped https://github.com/dry-rb/dry-struct/pull/75
=> use default value from settings Type 

lib/dry/system/component.rb, lib/dry/system/container.rb, spec/unit/loader_spec.rb
This makes it easier to provide a custom inflector. At the same time, this
change is not backward compatible with existing custom loaders since now their
constructors have to accept 2 arguments.
It's my first PR here, please be gentle!
=> Add inflector to container settings

lib/dry/system/booter.rb, lib/dry/system/container.rb, lib/dry/system/errors.rb, spec/integration/boot_spec.rb
Fixes #90 
@solnic @mainameiz I have added the `stop` method in `Container`.
It also raises an error when trying to stop a component that has not started yet.
=> add Container#stop

lib/dry/system/container.rb, spec/fixtures/lazy_loading/shared_root_keys/lib/kitten_service/fetch_kitten.rb, spec/fixtures/lazy_loading/shared_root_keys/lib/kitten_service/submit_kitten.rb, spec/fixtures/lazy_loading/shared_root_keys/system/boot/kitten_service.rb, spec/integration/container/lazy_loading/bootable_components_spec.rb
There was a bug where a resolution for an object using the same root key as a bootable component (e.g. resolving `"kitten_service.fetch_kitten"` where there is a bootable component named `:kitten_service`) would only allow the _first_ object resolution to work. Subsequent resolutions (e.g. for “kitten_service.submit_kitten”) would raise `Dry::Container::Error` with a message like `Nothing registered with the key "kitten_service.submit_kitten"` (even when this component did actually exist).
The problem exists only when using a non-finalized container (i.e. when the container is lazy loading components). On the first resolution, `Dry::System::Container.load_component` doesn’t detect that there is a bootable component on the root_key, and calls `.load_local_component`, which resolves the …
=> Bug fix: Allow multiple lazy resolutions using same root as bootable component

spec/spec_helper.rb
This is due to an issue reported in Truffleruby issues https://github.com/oracle/truffleruby/issues/1463
The problem lies in a fact, `pathname` is required by `codeclimate-test-reporter` gem working only under MRI. More clarified in this comment https://github.com/oracle/truffleruby/issues/1463#issuecomment-438401626 made by @eregon
This allows to run `dry-system` specs under Truffleruby
=> Require pathname in spec_helper.rb

lib/dry/system/booter.rb, lib/dry/system/container.rb, spec/integration/boot_spec.rb, spec/unit/container/boot_spec.rb
Fix #92 
@davydovanton @solnic I added the `shutdown!` method to stop all components.
I thought that if a component is not started, we shouldn't raise `ComponentNotStartedError` we simply skip it. My reason behind it is whatever the reason the user of `dry-system` for calling `shutdown!` is to stop everything, so if one component has not been stated it shouldn't affect, actually less work for us :)
=> Add Container#shutdown!

lib/dry/system/container.rb, spec/fixtures/require_path/lib/test/foo.rb, spec/unit/container_spec.rb
Per this [conversation](https://discourse.dry-rb.org/t/rails-development-and-dry-system/571/4), this change allows components like `dry-system-rails` to override the default strategy from using `Kernel#require` to `ActiveSupport::Dependencies::Loadable#require_dependency`.
E.g.
```ruby
class App < Dry::System::Container
class << self
def require_path(path)
require_dependency(path)
end
end
end
```
=> Wrap `require` statement in an extension method

.travis.yml
- update MRI patch versions
- include 2.6.1
- update to latest release of JRuby
- drop the unused `sudo: false` directive
- drop the `script` directive which was the default Travis action already
=> Travis: update CI matrix, include 2.6.1

lib/dry/system/auto_registrar.rb, lib/dry/system/booter.rb, lib/dry/system/components/bootable.rb, lib/dry/system/container.rb, lib/dry/system/manual_registrar.rb, lib/dry/system/provider.rb
The order of result of `Dit.glob/Dir.[]` varies depending on the FS. In general, it shouldn't matter, however, in practice it may lead to random-looking crashes across different environments (like macos vs linux etc).
=> Make dir listings order stable

Gemfile, lib/dry/system/auto_registrar.rb, lib/dry/system/components/bootable.rb, lib/dry/system/container.rb, lib/dry/system/lifecycle.rb, lib/dry/system/plugins/logging.rb, lib/dry/system/plugins/notifications.rb, spec/integration/container/plugins/logging_spec.rb, spec/unit/container/auto_register_spec.rb, spec/unit/container/import_spec.rb, spec/unit/container_spec.rb
This also adds `Container.registered?` which acts as `key?` used to.
Besides it, `Container.resolve` not takes an optional block to make this interface consistent with dry-container.
=> Attempt to lazy-load component when container is asked for `key?`

lib/dry/system/plugins/dependency_graph.rb, lib/dry/system/plugins/dependency_graph/strategies.rb
I still working on dry-system dependency graph plugin and found that current implementation use one notification. For example, we have 2 dry-system containers:
```ruby
class App < Dry::System::Container
use :dependency_graph
use :monitoring
configure do |config|
config.ignored_dependencies = %i[not_registered]
config.auto_register = %w[lib]
config.name = :main
end
load_paths!('lib')
end
class OtherApp < Dry::System::Container
use :dependency_graph
use :monitoring
configure do |config|
config.ignored_dependencies = %i[not_registered]
config.name = :new_one
config.auto_register = %w[]
end
end
```
In this case, these two containers will use one `notifications` object (which was created in the last container). For prevent this behavior we need to make this plugin immutable for each container. …
=> Make dependency plugin immutable for different dry-system containers

lib/dry/system/plugins.rb, spec/integration/container/plugins_spec.rb
And ensure that the Dry::System::Plugins.loaded_dependencies array doesn't contain duplicates
Previous to this, multiple plugins could load the same dependency by one including the dependency as a Pathname instance, and the other as a string. Dependencies would also be duplicated in the loaded_dependencies array even if they were already required
=> Ensure shared plugin dependencies are loaded once

lib/dry/system/container.rb
Today I realized I've been having `@__finalized__ = false` in my projects for ages 🤦‍♂
This is a reminder it's a good thing to have `config.warnings = true` in `spec_helper`
=> Set initial value for ivar

lib/dry/system/auto_registrar.rb, lib/dry/system/constants.rb, spec/unit/container/auto_register_spec.rb
Check that the directory in the `config.auto_register = %w[dir]` or `container.auto_register!('dir')` exists and fail if it's not.
I found it a bit confusing that `auto_register!('persistence')` didn't warn me that it should be `lib/persistence`.
=> Fail fast if auto_registrar config contains incorrect path

lib/dry/system/errors.rb, lib/dry/system/plugins.rb, spec/integration/container/plugins_spec.rb
This pull request fixes #132.
**Note:** I wasn't sure where to put the new `Dry::System::PluginNotFoundError` definition. There are two files that contain error definitions, `lib/dry/system/constants.rb` and `lib/dry/system/errors.rb` and the latter seemed like the correct place. In fact, I'm not really sure whether it makes sense to have error definitions in the constants file, so let me know if I can move them.
=> Misspelled plugin name raises meaningful error

lib/dry/system/constants.rb, lib/dry/system/errors.rb
This follows from the discussion about misplaced error definitions [here](https://github.com/dry-rb/dry-system/pull/135#issuecomment-576048485).
=> Centralize error definitions in `lib/dry/system/errors.rb`

lib/dry/system/container.rb, lib/dry/system/plugins.rb, lib/dry/system/plugins/bootsnap.rb, lib/dry/system/plugins/dependency_graph.rb, lib/dry/system/plugins/logging.rb, spec/integration/container/plugins_spec.rb
Previously a plugin would fail to initialize if during booting something already called `configure` with a block (which finalizes config and freezes it, so it's no longer possible to add new settings).
=> Use before(:configure) in plugins

docsite/source/index.html.md, docsite/source/settings.html.md
I understood that we don't have a documentation page about settings in dry-system. That's why I created this PR. I know that it's a raw page and we can make it better in the future. But I think it will be a good start if we merge it asap and update it in the next iteration. WDYT?
@solnic also, a question about documentation: should I update something else or it's enough?
=> Add information about built-in settings system

spec/fixtures/external_components/components/logger.rb, spec/integration/container/plugins/dependency_graph_spec.rb
**spec/integration/external_components**
The ExternalComponent::Loger class is defined in the :init block of components/logger, and the system under test has two booters:
- :logger
-  :my_logger
These booters are using the same external component, executing the :init proc twice as expected on the lifecycle.
Since the definition is executed (twice) in a proc triggered inside the RSpec example it escapes the removal done on the RSpec.before hook.
Using a guard avoid the redefinition, fixing the warnings.
**spec/integration/../dependency_graph_spec**
The removal of ExternalComponent module was missing, this should be done as we do on external_components_spec.rb
If accepted, will change the spec report from this:
To this:
=> Fix redefinition warnings happening on spec/integration

lib/dry/system/booter.rb, lib/dry/system/component.rb, lib/dry/system/components/bootable.rb, lib/dry/system/container.rb, lib/dry/system/errors.rb, spec/fixtures/multiple_bootable_dirs/custom_bootables/logger.rb, spec/fixtures/multiple_bootable_dirs/default_bootables/inflector.rb, spec/fixtures/multiple_bootable_dirs/default_bootables/logger.rb, spec/integration/container/bootable_components/multiple_bootable_dirs_spec.rb, spec/unit/container_spec.rb
This PR adds a `bootable_dirs` setting to `Dry::System::Container` and updates the `Booter` so that it finds boot files from one or more directories.
For each configured `bootable_dirs` entry, relative directories will be appended to the configured container root, and absolute directories will be left unchanged.
When searching for bootable files, the first match will win, and any subsequent same-named files will not be loaded. In this way, the bootable_dirs acts similarly to the $PATH in a shell environment.
This arrangement will support uses where a container vendor may want to ship their own “default” bootable components, but allow the _user_ of the container to replace any of them one by one. To achieve this, the user can add their own entry to the beginning of the bootable_dirs …
=> Support multiple boot file dirs

Gemfile, lib/dry/system/component.rb, lib/dry/system/container.rb, lib/dry/system/loader.rb, lib/dry/system/loader/autoloading.rb, spec/fixtures/autoloading/lib/test/entities/foo_entity.rb, spec/fixtures/autoloading/lib/test/foo.rb, spec/integration/container/autoloading_spec.rb, spec/integration/container/lazy_loading/bootable_components_spec.rb, spec/integration/container/lazy_loading/manual_registration_spec.rb, spec/unit/component_spec.rb, spec/unit/container/auto_register_spec.rb, spec/unit/container/hooks/load_path_hook_spec.rb, spec/unit/container/import_spec.rb, spec/unit/container/load_path_spec.rb, spec/unit/container_spec.rb, spec/unit/loader/autoloading_spec.rb, spec/unit/loader_spec.rb
This PR adds support for working with autoloaders like [Zeitwerk](http://github.com/fxn/zeitwerk).
It achieves this by:
- Moving the responsibility for requiring files away from `Container` (removing `.require_path`, **a breaking change**) and into the `Component` (as `Component#require!`), which itself delegates to the configured `Loader` (via `Loader#require!)
- Adding a new `Dry::System::Loader::Autoloading` loader, which can be configured to replace the default loader. This is identical to the default loader except that instead of requiring the component's file, it accesses the component's constant, which is a sufficient trigger for an autoloader like Zeitwerk to load the constant based on its own configuration
Along with this, it makes some internal changes and to rationalise some …
=> Add autoloader support, clarify load path handling

docsite/source/auto-import.html.md, docsite/source/booting.html.md, docsite/source/container.html.md, docsite/source/index.html.md
This is just a minimal set of changes to make sure the code in the docs reflects the new `component_dirs` setting (and related changes).
I also removed the code-formatting of "dry-system" throughout the docs (since it's the name of our gem, and not a code element).
=> Update docsite for component dirs

lib/dry/system/identifier.rb, spec/unit/identifier_spec.rb
The `identifier` of an `Identifier` is expected to be a String, but occasionally it might be a symbol passed through from `dry-container`. To be safe, cast it during initialization of the `Identifier` class.
This fixes a bug where resolving an unknown component provided as a Symbol (vs a String) would cause `gsub` `NoMethodError` error on `Symbol` and not the correct user-facing error about the component not being found.
Reproduction
```ruby
require "dry/system/container"
class Application < Dry::System::Container
configure do |config|
config.component_dirs.add "lib"
end
end
Application[:db]
```
Exception backtrace
```
/usr/local/bundle/bundler/gems/dry-system-7eb624a6ff65/lib/dry/system/identifier.rb:78:in `path': undefined method `gsub' for :db:Symbol (NoMethodError)
from …
```
=> Cast identifier to String during initialization

lib/dry/system/component_dir.rb, lib/dry/system/config/component_dir.rb, lib/dry/system/config/component_dirs.rb, lib/dry/system/container.rb, spec/integration/container/autoloading_spec.rb, spec/unit/config/component_dirs_spec.rb, spec/unit/container/auto_register_spec.rb
This PR rounds out the work done in #155, #157, and #158, and makes it possible to configure default values for all component dir settings directly on the container's `config.component_dirs`. For example:
```ruby
config.component_dirs.loader = MyCustomLoader
config.component_dirs.default_namespace = "my_app"
config.component_dirs.add "lib"
```
This will be particularly useful e.g. for users configuring dry-system to work with an class autoloader like Zeitwerk, which would require the following defaults to be applied:
```ruby
config.component_dirs.loader = Dry::System::Loader::Autoloading
config.component_dirs.add_to_load_path = false
```
Having to configure these manually for every added component dir would be a suboptimal configuration experience. Further, the existence of these default …
=> Allow custom system-wide defaults to be configured for all component dirs

changelog.yml
I'd like to release 0.19.0 later this week. The CHANGELOG entry is so massive I thought it would be worth running past you all as a check :)
=> Add changelog entry for 0.19.0

lib/dry/system/auto_registrar.rb, spec/unit/auto_registrar_spec.rb
This prevents "There is already an item registered with the key" Dry::Container::Error exceptions from being raised when finalizing the container after already having lazily loaded a few components.
This PR includes a new test case that would fail with the previous behaviour.
=> Check for actual registered string keys in AutoRegistrar

lib/dry/system/stubs.rb
Currently Container.enable_stubs! causes Container.finalize! signature to change:
method no longer accepts "freeze" keyword argument. This causes consumers that
rely on this api to crash, i.e. dry-rails railtie
=> Update finalize! signature in Container::Stubs

lib/dry/system/config/component_dir.rb, lib/dry/system/container.rb, lib/dry/system/plugins/bootsnap.rb, lib/dry/system/plugins/dependency_graph.rb, lib/dry/system/plugins/env.rb, lib/dry/system/plugins/logging.rb, spec/integration/container/plugins_spec.rb
This uses the new kwargs for the `setting` API, as well as updating our local override of the setting method to match its new params signature (it would be nice to see if we could remove that override, but that's a job for a separate PR).
This fix will be necessary to have in place by the time we release dry-configurable, since without these changes, the specs fail with the dry-configurable's master branch right now.
=> Update for latest dry-configurable

lib/dry/system/container.rb, lib/dry/system/plugins/logging.rb
This PR includes 2 changes:
- Use `ruby2_keywords` for our override of dry-configurable's `setting` method, to make sure it will still work to delegate to the original when provided "real" keyword arguments in newer Rubies 
- Update a setting in the logging plugin to provide a "real" hash literal (i.e. enclosed in curly braces) rather than rely on Ruby's implicit conversion of keyword args to a hash literal
With these changes in place, the dry-system test suite passes against both dry-configurable 0.12.1 (the latest released version) as well as the master branch (intended for release as 0.13.0), on both Ruby versions 3.0.1 and 2.7.3.
To prepare for the upcoming dry-configurable release (which is being planned for at https://github.com/dry-rb/dry-configurable/issues/120), we need to:
1. …
=> Make compatibility fixes to support a future dry-configurable 0.13.0 release

lib/dry/system/container.rb, lib/dry/system/plugins/logging.rb
This PR takes the changes from #186 and backports them on top of the most recent 0.18 series release, 0.18.1.
This will permit new releases of both the 0.18 and 0.19 series to ensure they both work with the upcoming dry-configurable 0.13.0.
=> Make compatibility fixes to support a future dry-configurable 0.13.0 release (for 0.18 series for releases)

docsite/source/settings.html.md
Since `Dry::System::Settings::DSL` is a `BasicObject`, it doesn’t include `Kernel`, so `#proc` is not defined.
To get this example working, call `Kernel.proc` directly
=> Fix settings component example code

lib/dry/system/plugins/bootsnap.rb
As per https://github.com/Shopify/bootsnap/commit/acefed8db9569b211d664f4165e277e1b26300aa, bootsnap is supported in all versions of Ruby >= 2.3, including head.
=> Allow bootsnap for Rubies up to 3.0.x

lib/dry/system/config/component_dir.rb, lib/dry/system/config/component_dirs.rb, lib/dry/system/config/namespace.rb, lib/dry/system/config/namespaces.rb, lib/dry/system/errors.rb, spec/integration/container/auto_registration/component_dir_namespaces/autoloading_loader_spec.rb, spec/integration/container/auto_registration/component_dir_namespaces/default_loader_spec.rb, spec/integration/container/auto_registration/component_dir_namespaces/multiple_namespaces_spec.rb, spec/unit/config/component_dirs_spec.rb, spec/unit/config/namespaces_spec.rb
This PR broadens the interfaces of both the `Dry::System::Config::ComponentDirs` and `Dry::System::Config::Namespaces` collection classes to make them more useful to external consumers looking to programatically construct and inspect these configurations. Specifically, it supports the addition of `source_dirs` config to Hanami in https://github.com/hanami/hanami/pull/1133.
The updated API for `Config::ComponentDirs` includes:
- `#dir` (also aliased as `#[]`) has been added, for retrieving previously added dirs by their paths
- `#add` now accepts a single `path_or_dir` argument, supporting two distinct usages:
- The existing usage, of providing a path string and then a block that is yielded a component dir object for that path, to be configured
- A new usage, where a whole component dir …
=> Broader interfaces to Config::ComponentDirs and Config::Namespaces

Gemfile, dry-system.gemspec, lib/dry/system/container.rb, project.yml
This is no longer needed given the change in dry-configurable at https://github.com/dry-rb/dry-configurable/pull/130.
=> Remove dry-configurable `setting` overload

lib/dry/system/component.rb, lib/dry/system/component_dir.rb, lib/dry/system/config/namespace.rb, lib/dry/system/constants.rb, lib/dry/system/container.rb, lib/dry/system/identifier.rb, lib/dry/system/importer.rb, spec/integration/container/auto_registration/component_dir_namespaces/deep_namespace_paths_spec.rb, spec/unit/identifier_spec.rb
Understanding "." as a key namespace separator is important to understanding dry-system behavior in general, and it is presumed across all our docs and other related material.
It does not make sense for our usage of dry-container for this to be configurable.
Resolves #192.
=> Expect key namespace separator to be "." at all times

lib/dry/system/container.rb, lib/dry/system/plugins/dependency_graph.rb, spec/integration/container/plugins/dependency_graph_spec.rb
This makes some changes to make the dependency graph plugin less intrusive on the overall container behaviour. It:
- Nests its setting underneath a top-level `dependency_graph` setting
- Removes the ambiguously named and potentially buggy (due to its ivars that may end up being set after the cotnainer is frozen) `Container.strategies` method and instead provides its custom auto-injector strategies via an overload of the container's public `.injector` method options.
=> Tidy the dependency graph plugin

lib/dry/system/provider/source.rb, spec/fixtures/external_components/components/mailer.rb, spec/fixtures/test/system/providers/client.rb
This can be (and has been) confused for activating plugins, which use the `use` method on the container, and given we now have consistent and easy-to-understand access to the target container via `target`, it's more straightforward to use `target.start :some_provider` instead of a provider source-specifiic method like `#use`.
In addition, this is more flexible, since you can also access the other lifecycle steps for providers now too, like `target.prepare :some_provider`.
=> Remove `use` method from provider source

lib/dry/system/provider.rb, lib/dry/system/provider/source.rb, spec/integration/container/providers/registering_components_spec.rb
This ensures that there is nothing different when registering in the provider from registreing directly on the target container.
Fixes #124.
=> Apply all options from provider registrations to registrations in target container

lib/dry/system/plugins/dependency_graph/strategies.rb, spec/integration/container/plugins/dependency_graph_spec.rb
This carries on from the work in #139 (thanks @davydovanton!) and expands upon the test suite to cover all injector strategies.
Closes #139.
=> Support all injector strategies for dependency graph plugin

lib/dry/system/component.rb, lib/dry/system/component_dir.rb, lib/dry/system/config/component_dir.rb, lib/dry/system/config/component_dirs.rb, spec/integration/container/auto_registration/custom_instance_proc_spec.rb
Adds a configurable `instance` proc on all component dirs, which was previously available only on the configuration object yielded to block given to `Container.auto_register!`, removed in 0.19.0 to make way for consistently behaving and configurable component dirs.
Now users have two ways to customise component instantiation: the `instance` proc for simple cases, or a full replacement `loader` for more advanced cases.
Fixes #180.
=> Restore support for configurable instance proc

lib/dry/system/container.rb, lib/dry/system/provider_registrar.rb, spec/integration/container/providers/conditional_providers_spec.rb
Allow providers to be conditionally registered based on a new `if:` argument for `Container.register_provider`.
The value for `if:` is expected to be a simple truthy or falsey value only. It defaults to `true` when not provided.
This feature is valuable because it allows certain providers, which may only be needed in certain runtime contexts (i.e. when the container is left lazy loading and those providers or dependent components are accessed directly) to be skipped when finalizing the container to run the "main" parts of the app. For example, there may be a provider required purely for a subset of background jobs, which will be loaded when running the jobs worker, but is not needed at all when the main web application is run via Puma and a finalised container.
In this PR we also move all …
=> Conditional providers

lib/dry/system/plugins.rb, lib/dry/system/plugins/env.rb, lib/dry/system/plugins/zeitwerk.rb
This is useful if external integrating systems (e.g. Hanami) want to use the Zeitwerk plugin for configuring the loader, but want to call `#setup` at a different time.
=> Allow Zeitwerk::Loader#setup to be run externally

lib/dry/system/manifest_registrar.rb, spec/integration/container/auto_registration/component_dir_namespaces/autoloading_loader_spec.rb, spec/integration/container/lazy_loading/manifest_registration_spec.rb, spec/support/zeitwerk_helpers.rb
`#finalize!` is sending the basename directly to `#call`, which expects a `Dry::System::Identifier`.
This means that if you configure a `registrations_dir`, putting any file in that directory will lead to an exception during finalization.
This appears to have been introduced during #181
=> Fix incorrect type in ManifestRegistrar#finalize!

lib/dry/system/component.rb, lib/dry/system/component_dir.rb, spec/unit/component_spec.rb, spec/unit/loader/autoloading_spec.rb, spec/unit/loader_spec.rb
This is useful for users setting up auto-registration rules based on file paths.
=> Expose Component#file_name

Gemfile, lib/dry/system/container.rb, spec/integration/container/lazy_loading/auto_registration_disabled_spec.rb, spec/integration/container/providers/conditional_providers_spec.rb
This makes things work again with dry-container from main:
- Use the new `Dry::Container::KeyError` (`Error` is deprecated)
- Require `dry/configurable` before `dry/container` so that `Configurable` is used as the config backend
=> Fix compat with dry-container from main

lib/dry/system/container.rb, spec/integration/container/importing/container_registration_spec.rb, spec/integration/container/importing/import_namespaces_spec.rb
With this change, we can import components from one container to the root of another by providing a namespace of `nil` to the `import` directive:
```ruby
class MyContainer < Dry::System::Container
import from: SomeOtherContainer, as: nil
end
```
Generally, having your imports namespaced is a good practice, because it serves as a clear hint as to their origin. However, in some cases, it may be useful not to have a namespace. One such case is in our plans for Hanami 2.0, where we want a small selection of application-wide components (such as `"logger"` and `"inflector"`) to be available to every container with the same keys, so there can a consistency in the way they are addressed.
=> Import root components via `nil` import namespace

Gemfile, dry-system.gemspec, lib/dry/system/config/component_dir.rb, lib/dry/system/config/namespaces.rb, lib/dry/system/container.rb
The main change here is that we stop relying on `Dry::Configurable::Config` internal implementation details by using the new `#configured?` API introduced in https://github.com/dry-rb/dry-configurable/pull/143.
While we're here, we make one other small tweak to improve dry-configurable compatibility: use dry-configurable's class-level `#finalize` instead of `Config#finalize` directly, which will mean that we'll continue to have correct behaviour if dry-configurable ever moves any additional logic to this class-level method.
=> Update for dry-configurable settings separation

lib/dry/system/provider_sources/settings/config.rb, spec/integration/deprecations/deprecated_settings_provider_source_key_spec.rb, spec/integration/settings_component_spec.rb
Resolves #245 
This is probably not the right way to solve this, but it gives the intended effect.
=> Validate settings even if loader does not set value

lib/dry/system/plugins/notifications.rb
Without this change, we were getting errors like this when loading the notifications plugin:
```
NameError:
uninitialized constant Dry::Monitor::Clock
```
=> Use main dry/monitor entrypoint for autoloading

spec/support/zeitwerk_helpers.rb
`Zeitwerk::Registry` is a private module. This is the place where Zeitwerk internally stores state that is global. For example, given this file to be required, is it managed by any loader? If yes, which one? This is all internal.
The private method `Zeitwerk::Registry.loaders` is going to disappear, and I'd like to volunteer this patch so that your test suite continues being green when it ships.
By design, Zeitwerk hides the loaders. That is, the library does not provide interface to reach that collection, and that is deliberate. If I am a gem author and I load my code with a loader, I am the only one in the entire process owning this thing. Accessing that loader from outside is not something that should be normalized by the API.
I am not saying this is going to be my design guideline …
=> Remove usage of the private Zeitwerk::Registry.loaders

lib/dry/system/loader.rb, spec/fixtures/components_with_errors/test/constant_error.rb, spec/integration/did_you_mean_integration_spec.rb
Without this, *any* NameError (including NoMethodError) will go through the DidYouMean integration and
it will fail since that code expects only a Constant, not any name (including "undefined local variable or method")
Instead, this code will ensure we only try to do that when we get a NameError for specifically trying to load the constant we're looking for. Everything else will be re-raised and go through the normal flow (including any more DidYouMean default behavior).
Fixes hanami/hanami#1252. (Specifically see [this comment](https://github.com/hanami/hanami/issues/1252#issuecomment-1315898878))
Bug introduced in #217
Thoughts on whether we should test this? We could create a fixture file to load a component that has a NameError in it and ensure that error passes through instead of …
=> Only use DidYouMean-integrated Error for Component loading failure

docsite/source/external-provider-sources.html.md
Current [docs example](https://dry-rb.org/gems/dry-system/1.0/external-provider-sources/)
```ruby
Dry::System.register_provider_sources(:common, boot_path: File.join(__dir__, "provider_sources"))
```
[Method definition](https://github.com/dry-rb/dry-system/blob/a4ef6decf230c4c0adf81fb61ee7c47e17bf0a93/lib/dry/system.rb#L26)
```ruby
#
def self.register_provider_sources(path)
provider_sources.load_sources(path)
end
```
Updated docs to match method definition
=> Update docs example of Dry::System.register_provider_sources

lib/dry/system/provider_registrar.rb, spec/integration/container/providers/custom_provider_registrar_spec.rb
In `ProviderRegistrar`, create a new `target_container` (an alias of its `container` attribute), and use this `target_container` when creating providers.
This makes it possible for users of dry-system to provide a subclass of the `ProviderRegistrar` where they can customise the target_container that their providers receive.
We need this so that providers in Hanami can receive their respective slice as the `target`, making it possible for code inside the provider to interact naturally with the Hanami slice itself, as opposed to its internal container (which itself knows nothing about the broader Hanami app).
As part of this change, make `ProviderRegistrar` and `ProviderRegistrar#target_container` both public API (with everything else about the provider registrar still remaining private). …
=> Use target_container alias to pass to providers

lib/dry/system.rb, lib/dry/system/provider_registrar.rb, lib/dry/system/provider_source_registry.rb, spec/integration/container/providers/provider_sources/provider_options_spec.rb
When registering a provider source, you can now provider a `provider_options:` containing a hash of default options for providers to be registered using that source.
The one provider option currently supported is `namespace:`.
Allowing a provider source to specify e.g. `provider_options: {namespace: true}` is useful if the source will register multiple components at different keys. In such a case, the provider will typically want to have a `namespace: true` provider option.
Specifying this option at the time of provider source registration then makes for a simpler and less error-prone experience when the user eventually registers a provider using that source. The user now no longer needs to remember to provide their own explicit `namespace: true`.
=> Allow provider sources to specify provider options

lib/dry/system/container.rb, lib/dry/system/provider_registrar.rb
Move the logic from `ProviderRegistrar#find_and_load_provider` straght into `#[]` for a more convenient and reliable experience when interacting with providers.
Having `#[]` either return a provider or nil without attempting to _load_ the provider was a potential source of confusion. Now it can work as the one and only interface for fetching a provider.
Remove the `#provider` alias for `#[]` since this was private and unused (and unnecessary).
Remove `#start_provider_dependency` (which was the only thing in `ProviderRegistrar` dealing with components instead of providers and instead invoke its internal logic (a one-liner, anyway!) directly in `Container#load_component`.
=> Load providers when accessing via `ProviderRegistrar#[]`

lib/dry/system/provider.rb, lib/dry/system/provider/source.rb, lib/dry/system/provider_registrar.rb, spec/integration/container/providers/custom_provider_superclass_spec.rb
Relates to hanami/hanami#1417
The motivation for this is to allow consuming frameworks of dry-system to define their own superclass for providers, in order to add their own method apis to the class.
This is only used for user-defined providers with a block implementation.
External providers in a group do not allow this, because their superclass is defined ahead of time when they are added to the source registry. If an external provider source wants to use a different superclass, they can define a concrete class of their own instead.
The custom superclass is assumed to be a child of
Dry::System::Provider::Source.
=> Allow Provider Sources to choose a custom superclass

lib/dry/system/provider_registrar.rb
This was used by earlier 2.x versions of Hanami, so usage is out in the wild. We should maintain this method to ensure nothing breaks.
=> Restore find_and_load_provider method as an alias

lib/dry/system/plugins/bootsnap.rb
Bootsnap has since dropped support for < 2.6.0, and supports up to 3.2
Use the actual Gem::Specification so this isn't hard-coded.
I believe this is a more future-proof approach than #264
=> Use bootsnap's gemspec to determine availability

docsite/source/container.html.md, docsite/source/container/hooks.html.md, lib/dry/system/container.rb, spec/unit/container/hooks/after_hooks_spec.rb
This is a (long-overdue) followup PR to [our conversation](https://discourse.hanamirb.org/t/newrelic-apm-on-hanami-2/872) related to integrating APM into a Dry-System app.
Also relates to hanami/hanami#1360
**Use Case:** I want to be able to dynamically decorate keys as they are added into the container system in order to perform APM metrics without having to touch every file.
**Use Case:** I want to audit the usage of particular namespaces in the Container using Dry-Monitor decoration, such as producing an audit log of Authorization checks.
In these use-cases, it's important that I want to react to container registration without having knowledge of precisely what keys are being registered. The decorate feature works well when keys are known in advance, but otherwise you have to enumerate …
=> Make Container hooks more useful for dynamic registration

lib/dry/system/manifest_registrar.rb, spec/integration/container/lazy_loading/manifest_registration_spec.rb
This is a bug that is caused by the interaction between dry-system and dry-rails.
Dry::Rails rebuilds the Container from scratch on every reload, which resets all the keys. Since ManifestRegistrar was using `require`, this reload would not register the keys as expected.
=> ManifestRegistrar uses load instead of require

lib/dry/system/container.rb, lib/dry/system/importer.rb
We were checking for an import namespace using a component `root_key`, which is a symbol, whereas the importer was expecting strings. This led to imported components only becoming available on a full boot, not when lazy loading properly (because the check for their namespace in the importer would always return false due to the type mismatch).
This will resolve https://github.com/hanami/hanami/issues/1529.
=> Fix lazy loading of imported components
